---
name: Build MSPDebug and libMSP430 for linux

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mspdebug:
    name: Build MSPDebug
    runs-on: ubuntu-latest

    steps:    
      - name: Install required libraries
        run: |
          sudo apt-get install libusb-1.0-0-dev libusb-dev libboost1.74-all-dev libhidapi-dev
        
      - name: Checkout libboost 1.74 patch
        uses: actions/checkout@v3.0.0
        
      - name: Checkout MSPDebug code
        run: |
          git clone https://github.com/dlbeer/mspdebug.git
      
      - name: Build MSPDebug
        run: |
          cd mspdebug
          ls -la .
          make
          sudo make install
          
      - name: Download libMSP430 code and patch
        run: |
          cd mspdebug
          ls -la .
          wget https://dlbeer.co.nz/articles/slac460y/slac460y-linux.patch
          mkdir libmsp430
          cd libmsp430
          ls -la .
          wget http://www.ti.com/lit/sw/slac460y/slac460y.zip
          unzip slac460y.zip
          rm slac460y.zip
          ls -la ..
          patch -p1 < ../slac460y-linux.patch
          patch -p1 < ../libboost-1.74.patch
          
      - name: Build libMSP430
        run: |        
          ls -la .
          cd mspdebug/libmsp430
          make
          sudo make install
